# Generated by Django 5.1.3 on 2025-03-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0003_hostelstay_city_hostelstay_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostelstay",
            old_name="end_date",
            new_name="check_in",
        ),
        migrations.RenameField(
            model_name="hostelstay",
            old_name="guardian_mobile",
            new_name="guardian_no",
        ),
        migrations.RenameField(
            model_name="hostelstay",
            old_name="payment_due",
            new_name="total_months",
        ),
        migrations.RenameField(
            model_name="hostelstay",
            old_name="user_mobile",
            new_name="your_mobile",
        ),
        migrations.RemoveField(
            model_name="hostelstay",
            name="share_type",
        ),
        migrations.RemoveField(
            model_name="hostelstay",
            name="start_date",
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="check_out",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="room_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="share",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="hostelstay",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="hostelstay",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
