# Generated by Django 5.1.3 on 2025-03-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0004_rename_end_date_hostelstay_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostelstay",
            name="payment_due",
            field=models.IntegerField(default=0),
        ),
    ]
