# Generated by Django 5.1.3 on 2025-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0005_hostelstay_payment_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostelstay",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
