# Generated by Django 5.1.3 on 2025-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0008_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="admin_message",
            field=models.TextField(default=True),
        ),
    ]
