# Generated by Django 5.1.3 on 2025-03-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0010_alter_chatmessage_admin_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_admin_reply",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="admin_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
