# Generated by Django 5.1.3 on 2025-03-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0011_remove_chatmessage_is_admin_reply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostelstay",
            name="priority1",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="priority2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="priority3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="unique_id",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hostelstay",
            name="location",
            field=models.CharField(
                choices=[
                    ("Choose", "Choose"),
                    ("Hyderabad", "hyderabad"),
                    ("Chennai", "Chennai"),
                ],
                default="Choose",
                max_length=100,
            ),
        ),
    ]
