# Generated by Django 5.1.3 on 2025-03-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0013_remove_hostelstay_city_hostelstay_hosteltype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostelstay",
            name="share",
            field=models.IntegerField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                default="5",
            ),
        ),
    ]
