# Generated by Django 5.1.3 on 2025-03-15 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0014_alter_hostelstay_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostelstay",
            old_name="priority2",
            new_name="assigned_hostel",
        ),
        migrations.RemoveField(
            model_name="hostelstay",
            name="priority1",
        ),
        migrations.RemoveField(
            model_name="hostelstay",
            name="priority3",
        ),
        migrations.AlterField(
            model_name="hostelstay",
            name="location",
            field=models.CharField(
                choices=[
                    ("choose", "Choose"),
                    ("Hyderabad", "Hyderabad"),
                    ("Chennai", "Chennai"),
                ],
                default="Choose",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="hostelstay",
            name="share",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                default="5",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="HostelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority1", models.CharField(max_length=255)),
                ("priority2", models.CharField(blank=True, max_length=255, null=True)),
                ("priority3", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hostel_stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="hostel.hostelstay",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
