# Generated by Django 5.1.3 on 2025-03-15 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0015_rename_priority2_hostelstay_assigned_hostel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostelpreference",
            name="hostel_stay",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferences",
                to="hostel.hostelstay",
            ),
        ),
    ]
