# Generated by Django 5.1.3 on 2025-03-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0016_alter_hostelpreference_hostel_stay"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostelstay",
            name="priority1",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="priority2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hostelstay",
            name="priority3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="HostelPreference",
        ),
    ]
