# Generated by Django 5.1.3 on 2025-03-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0019_outing"),
    ]

    operations = [
        migrations.AddField(
            model_name="outing",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="outing",
            name="reason",
            field=models.TextField(),
        ),
    ]
