# Generated by Django 5.1.3 on 2025-03-15 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0021_remove_outing_date_remove_outing_return_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outing",
            name="indate",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="outing",
            name="intime",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 3, 15, 5, 3, 20, 497416, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="outing",
            name="outdate",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="outing",
            name="outtime",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 3, 15, 5, 3, 20, 497416, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
